sudo: required

services:
  - docker

before_install:
  - docker build -t vashenko49/docker-react -f Dockerfile.dev .

script:
  - docker run vashenko49/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-travis"
  env: "Dockerreacttravis-env"
  bucket_name: "docker-react-s3"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

